roon_enabled: false
roon_available_externally: false

# directories
roon_data_directory: "{{ docker_home }}/roon"
roon_cache_directory: "{{ docker_home }}/roon_cache"
roon_music_directory: "{{ music_root }}"

# uid / gid
roon_user_id: "1000"
roon_group_id: "1000"

# network
roon_hostname: "roon"
roon_network_name: "roon_network"

# docker
roon_container_name: "roon"
roon_image_name: "elgeeko/roon-server"
roon_image_version: "latest"

# specs
roon_memory: 1g